version: '3.7'
services:

    reverse-proxy:
        image: traefik
        restart: always
        container_name: traefik
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./traefik.toml:/traefik.toml
            - ./acme.json:/acme.json
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    web:
        external: true
